version: '3.9'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb_server
    environment:
      INFLUXDB_DB: dms
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: /run/secrets/influxdb_admin_password
      INFLUXDB_TOKEN: /run/secrets/influxdb_admin_token
      INFLUXDB_ORG: dms_org
      INFLUXDB_BUCKET: dms_bucket
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb_server:27017/
    depends_on:
      - mongodb

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: dms
      MYSQL_USER: dms_admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt
  mongodb_root_password:
    file: ./secrets/mongodb_root_password.txt
  influxdb_admin_password:
    file: ./secrets/influxdb_admin_password.txt
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token.txt

volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
  influxdb_data:
    driver: local
