version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password # Root password via secret
      MYSQL_DATABASE: dms
      MYSQL_USER: dms_admin
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password # Non-root user password via secret
    secrets:
      - mysql_root_password
      - mysql_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt # Path to the file for root password
  mysql_user_password:
    file: ./secrets/mysql_user_password.txt # Path to the file for non-root user password

volumes:
  mysql_data:
    driver: local
